@echo off

@REM Creating virtual environment...
echo Creating virtual environment...
python -m venv .venv

@REM Activating virtual environment...
echo Activating virtual environment...
call .\.venv\Scripts\activate

@REM Installing requirements...
echo Installing requirements...
pip install -r requirements.txt

@REM Process completed.
echo Process completed.